name: treat_min
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  carousel_slider: ^2.3.1
  flutter_verification_code: ^0.2.1
  step_progress_indicator: ^0.2.5+8
  flutter_gallery: ^2.4.0+20400
  custom_switch_button: ^0.5.0
  toggle_switch: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
